name: Deploy to VPS
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install dependencies
      run: npm ci
  update:
    name: Update
    runs-on: ubuntu-18.04
    needs: [build]
    steps:
    - name: Run script on VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        debug: true
        script_stop: true
        script: |
          pm2 stop emerald
          bash ~/scripts/update-emerald.sh
          pm2 start ~/scripts/emerald.sh
